---
- name: Create Database Schema in AWS RDS
  hosts: local
  vars:
    db_instance_endpoint: "terraform-20240627075733469800000001.c7ko42wuoka1.us-east-1.rds.amazonaws.com"
    db_instance_port: 3306
    db_name: "studentapp"
    db_user: "admin"
    db_password: "admin123"
  tasks:
    - name: Install MySQL client and Python pip
      ansible.builtin.apt:
        name: 
          - mysql-client
          - python3-pip
        state: present

    - name: Create database schema
      community.mysql.mysql_db:
        login_host: "{{ db_instance_endpoint }}"
        login_port: "{{ db_instance_port }}"
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        name: "{{ db_name }}"
        state: present
    
    - name: Create table in the database schema
      community.mysql.mysql_db:
        name: "{{ db_name }}"
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_host: "{{ db_instance_endpoint }}"
        query: >
          CREATE TABLE if not exists students(
            student_id INT NOT NULL AUTO_INCREMENT,student_name VARCHAR(100) NOT NULL,
            student_addr VARCHAR(100) NOT NULL,student_age VARCHAR(3) NOT NULL,student_qual VARCHAR(20) NOT NULL,student_percent VARCHAR(10) NOT NULL,student_year_passed VARCHAR(10) NOT NULL,PRIMARY KEY (student_id)
          );



