---
- name: Create Database Schema in AWS RDS
  hosts: localhost
  vars:
    db_instance_endpoint: "terraform-20240626152833955600000001.c7ko42wuoka1.us-east-1.rds.amazonaws.com"
    db_instance_port: 3306
    db_name: "studentapp"
    db_user: "admin"
    db_password: "admin123"
  tasks:
    - name: Install MySQL client and Python pip
      ansible.builtin.apt:
        name: 
          - mysql-client
          - python3-pip
        state: present

    - name: Ensure MySQL Python library is installed
      pip:
        name: pymysql
        state: present

    - name: Create database schema
      community.mysql.mysql_db:
        login_host: "{{ db_instance_endpoint }}"
        login_port: "{{ db_instance_port }}"
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        name: "{{ db_name }}"
        state: present
