---
- name: Install MariaDB and create schema
  hosts: localhost
  become: yes

  vars:
    mysql_root_password: 1
    db_name: studentapp
    db_user: sameer
    db_password: 1234

  tasks:
    - name: Install MariaDB server
      apt:
        name: mariadb-server
        state: present
      tags: 
        - mariadb

    - name: Secure MariaDB installation (optional)
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        user: root
        password: "{{ mysql_root_password }}"
        host: localhost
        priv: "*.*:ALL,GRANT"
        state: present
      tags: 
        - mariadb

    - name: Create database schema
      mysql_db:
        name: "{{ db_name }}"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"
      tags: 
        - mariadb

    - name: Create database user
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: "{{ db_name }}.*:ALL"
        host: localhost
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"
      tags: 
        - mariadb
