---
- name: Install MariaDB and create schema
  hosts: localhost
  become: yes

  vars:
    db_name: studentapp

  tasks:
    - name: Install MariaDB server
      apt:
        name: mariadb-server
        state: present
      tags: 
        - mariadb

    - name: Create database schema
      mysql_db:
        name: "{{ db_name }}"
        state: present
        login_user: root
      tags: 
        - mariadb
