---
- name: Install Tomcat
  hosts: localhost
  tasks:
    - name: Update APT package index
      apt:
        update_cache: yes
    - name: Install OpenJDK 11
      apt:
        name: openjdk-11-jdk
        state: present
    - name: Create Tomcat group
      group:
        name: tomcat

    - name: Create Tomcat user
      user:
        name: tomcat
        group: tomcat
        home: /opt/tomcat
        shell: /bin/false
    - name: Download Tomcat
      get_url:
        url: "https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.90/bin/apache-tomcat-9.0.90.tar.gz"
        dest: /opt/tomcat
    - name: Create Tomcat directory
      file:
        path: /opt/tomcat
        state: directory
        owner: sameer
        group: sameer
    - name: Extract Tomcat in opt
      unarchive:
        src: /opt/tomcat/apache-tomcat-9.0.90.tar.gz
        dest: /opt/tomcat
        remote_src: yes
    - name: Set permissions on Tomcat directory
      file:
        path: /opt/tomcat/apache-tomcat-9.0.90
        state: directory
        owner: sameer
        group: sameer
        recurse: yes
    - name: Ensure Tomcat is executable
      file:
        path: /opt/tomcat/apache-tomcat-9.0.90/bin/catalina.sh
        mode: '0755'
        owner: sameer
        group: sameer
    - name: Download jar file and store in lib
      get_url:
        url: "https://s3-us-west-2.amazonaws.com/studentapi-cit/mysql-connector.jar"
        dest: /opt/tomcat/apache-tomcat-9.0.90/lib
    - name: Download war file and store in webapps
      get_url:
        url: "https://s3-us-west-2.amazonaws.com/studentapi-cit/student.war"
        dest: /opt/tomcat/apache-tomcat-9.0.90/webapps
    - name: Add a Resource element for JDBC DataSource
      blockinfile:
        path: /opt/tomcat/apache-tomcat-9.0.90/conf/context.xml
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
        insertafter: "<Context>"
        block: |
          <Resource name="jdbc/YourDB"
                    auth="Container"
                    type="javax.sql.DataSource"
                    maxTotal="100"
                    maxIdle="30"
                    maxWaitMillis="10000"
                    username="root"
                    password="1234"
                    driverClassName="com.mysql.jdbc.Driver"
                    url="jdbc:mysql://localhost:3306/studnetapp"/>
   - name: Start the script
      shell: /opt/tomcat/apache-tomcat-9.0.90/bin/catalina.sh start